/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package COMPROBARVALIDACION;
import java.awt.Color;
import javax.swing.JOptionPane;
import vacio.comprobacion;
/**
 *
 * @author VictorMTA
 */
public class camposvalidacion extends javax.swing.JFrame {
comprobacion v = new comprobacion();

    /**
     * Creates new form camposvalidacion
     */
    public camposvalidacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A = new javax.swing.JTextField();
        B = new javax.swing.JTextField();
        C = new javax.swing.JTextField();
        D = new javax.swing.JTextField();
        LNombre = new javax.swing.JLabel();
        LapeP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ed1 = new javax.swing.JTextField();
        LMensaje = new javax.swing.JLabel();
        Fecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        A.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                AComponentAdded(evt);
            }
        });
        A.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                ACaretUpdate(evt);
            }
        });
        A.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                AInputMethodTextChanged(evt);
            }
        });
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        A.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AKeyTyped(evt);
            }
        });

        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        B.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BKeyReleased(evt);
            }
        });

        C.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                CInputMethodTextChanged(evt);
            }
        });
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CKeyReleased(evt);
            }
        });

        D.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DKeyReleased(evt);
            }
        });

        LNombre.setText("nombre");

        LapeP.setText("apellido paterno");

        jLabel3.setText("apellido Materno");

        jLabel4.setText("correo");

        jButon.setText("VALIDAR");
        jButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButonActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha nacimiento DD/MM/AA");

        jLabel6.setText("Edad");

        Ed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ed1ActionPerformed(evt);
            }
        });
        Ed1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Ed1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Ed1KeyReleased(evt);
            }
        });

        Fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FechaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FechaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LapeP)
                                    .addComponent(jLabel3))
                                .addGap(2, 2, 2)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ed1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(LMensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButon)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LapeP)
                    .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Ed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButon)
                    .addComponent(LMensaje))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_BActionPerformed

    private void jButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButonActionPerformed

       if (v.comprobarCajaTexto(A,B,C,Ed1,Fecha,D))
        {
            JOptionPane.showMessageDialog(this,"Campos Vacios, Faltan Datos");
       }else{
           //Probar Fecha
        if (v.comprobarFecha(Fecha))
        {
            
        }else{
              JOptionPane.showMessageDialog(this,"Campos fecha no valido");
          }
        
        //Probar Email
         if (v.comprobarEmail(D))
        {
            
        }else{
           JOptionPane.showMessageDialog(this,"Campo email no valido");
       }
         if(v.comprobarINT(Ed1)) {
            
        }else{
             JOptionPane.showMessageDialog(this,"los datos en edad no son validos");
            
        }
         
          if (v.comprobarString(A)&&v.comprobarString(B)&&v.comprobarString(C)){
        A.setForeground(Color.BLACK);
        B.setForeground(Color.BLACK);
        B.setForeground(Color.BLACK);
     }else{  
        A.setForeground(Color.red);
        B.setForeground(Color.red);
        C.setForeground(Color.red);
         JOptionPane.showMessageDialog(this,"Favor de verifique y Corriga los los campos en rojo iniciando con Letra Mayuscula o NO ingesando numeros");
       
     }
        
       }

    

        
    }//GEN-LAST:event_jButonActionPerformed

    private void ACaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_ACaretUpdate
    
    
        // TODO add your handling code here:
    }//GEN-LAST:event_ACaretUpdate

    private void AInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_AInputMethodTextChanged
     
        
        
    }//GEN-LAST:event_AInputMethodTextChanged

    private void AKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AKeyTyped
       
       
    }//GEN-LAST:event_AKeyTyped

    private void AKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AKeyPressed
        //this.LMensaje.setText("");
        if (v.comprobarString(A))
        {
           A.setForeground(Color.black);
            //this.LMensaje.setText("");
            
        }else{
             // LMensaje.setText("Campos Nombre no valido");
              A.setForeground(Color.red);
          }
      
             
             
             
                // LMensaje.setText("");
             
          
    }//GEN-LAST:event_AKeyPressed

    private void BKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BKeyPressed
       this.LMensaje.setText("");
        if (v.comprobarString(B))
        {
            // LMensaje.setText("");
             B.setForeground(Color.black);
        }else{
          //    LMensaje.setText("Campos Apellido Paterno no valido");
              B.setForeground(Color.red);
          }
        //LMensaje.setText("");
    }//GEN-LAST:event_BKeyPressed

    private void CKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CKeyPressed
        
        //this.LMensaje.setText(""); 
        if (v.comprobarString(C))
        {
          //   LMensaje.setText("");
             C.setForeground(Color.black);
        }else{
        //      LMensaje.setText("Campos Apellido Materno no valido inicie  con letra mayuscula");
              C.setForeground(Color.red);
          }
        //  LMensaje.setText("");
    }//GEN-LAST:event_CKeyPressed

    private void Ed1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ed1KeyPressed
      //this.LMensaje.setText("");
        
        if (v.comprobarINT(Ed1))
        {
        //     LMensaje.setText("");
             Ed1.setForeground(Color.black);
        }else{
      //        LMensaje.setText("Campos Edad no valido");
              Ed1.setForeground(Color.red);
          }
        //  LMensaje.setText("");
    }//GEN-LAST:event_Ed1KeyPressed

    private void DKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DKeyPressed
//             this.LMensaje.setText("");
        if (v.comprobarEmail(D))
        {
           // this. LMensaje.setText("");
             D.setForeground(Color.black);
        }else{
             // LMensaje.setText("Campos Email no valido");
              D.setForeground(Color.red);
          }
       // LMensaje.setText("");
    }//GEN-LAST:event_DKeyPressed

    private void AKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AKeyReleased

 this.LMensaje.setText("");
        if (v.comprobarString(A))
        {
           A.setForeground(Color.black);
            //this.LMensaje.setText("");
            
        }else{
              //LMensaje.setText("Campos Nombre no valido");
              A.setForeground(Color.red);
          }
        this.LMensaje.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_AKeyReleased

    private void CKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CKeyReleased
//this.LMensaje.setText(""); 
        if (v.comprobarString(C))
        {
          //   LMensaje.setText("");
             C.setForeground(Color.black);
        }else{
              //LMensaje.setText("Campos Apellido Materno no valido inicie  con letra mayuscula");
              C.setForeground(Color.red);
          }
        //LMensaje.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_CKeyReleased

    private void Ed1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ed1KeyReleased
//this.LMensaje.setText(""); 
        if (v.comprobarINT(Ed1))
        {
           //  LMensaje.setText("");
             Ed1.setForeground(Color.black);
        }else{
             // LMensaje.setText("Campos edad no valido");
              Ed1.setForeground(Color.red);
          }
//LMensaje.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_Ed1KeyReleased

    private void DKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DKeyReleased
//this.LMensaje.setText("");
        if (v.comprobarEmail(D))
        {
             //LMensaje.setText("");
             D.setForeground(Color.black);
        }else{
             // LMensaje.setText("Campos Apellido Paterno no valido");
              D.setForeground(Color.red);
          }
//LMensaje.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_DKeyReleased

    private void BKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BKeyReleased
//this.LMensaje.setText("");
        if (v.comprobarString(B))
        {
            // LMensaje.setText("");
             B.setForeground(Color.black);
        }else{
             // LMensaje.setText("Campos Apellido Paterno no valido");
              B.setForeground(Color.red);
          }
        //LMensaje.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_BKeyReleased

    private void FechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FechaKeyPressed
//this.LMensaje.setText("");
        if (v.comprobarFecha(Fecha))
        {
            // LMensaje.setText("");
             Fecha.setForeground(Color.black);
        }else{
             // LMensaje.setText("Campos Apellido Paterno no valido");
              Fecha.setForeground(Color.red);
          }
       // LMensaje.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaKeyPressed

    private void FechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FechaKeyReleased
       //this.LMensaje.setText("");
       
       
        if (v.comprobarFecha(Fecha))
        {
             //LMensaje.setText("");
             Fecha.setForeground(Color.black);
        }else{
             //LMensaje.setText("Campo Edad no valido Favor de ingresar datos o corregir");
              Fecha.setForeground(Color.red);
          }
        //LMensaje.setText("");
        
// TODO add your handling code here:
    }//GEN-LAST:event_FechaKeyReleased

    private void AComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_AComponentAdded

        // TODO add your handling code here:
    }//GEN-LAST:event_AComponentAdded

    private void CInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_CInputMethodTextChanged

    }//GEN-LAST:event_CInputMethodTextChanged

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_CActionPerformed

    private void Ed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ed1ActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(camposvalidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(camposvalidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(camposvalidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(camposvalidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new camposvalidacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private javax.swing.JTextField D;
    private javax.swing.JTextField Ed1;
    private javax.swing.JTextField Fecha;
    private javax.swing.JLabel LMensaje;
    private javax.swing.JLabel LNombre;
    private javax.swing.JLabel LapeP;
    private javax.swing.JButton jButon;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
